(()=>{
'use strict';
const HOME={lat:51.39638,lng:-0.44487};
const BBOX={s:51.3898529,w:-0.4856386,n:51.4234539,e:-0.3913135};
const M_PER_DEG=111320, COS=Math.cos(HOME.lat*Math.PI/180);
const WALK_MPS=1.20;
const PLAYER_RADIUS=.34;
let speedMult=1, ppm=11, loaded=false, loadError=false;
const MIN_PPM=4.5,MAX_PPM=24;
let cam={x:-7.2,y:.6};
let world={roads:[],paths:[],buildings:[],land:[],parking:[],rails:[],barriers:[],water:[],bounds:null};

const css=document.createElement('style');css.textContent=`
#game #canvas{display:block!important;position:absolute;inset:0;z-index:1;background:#35533d;touch-action:none}#game #realMap,.map-tools,.map-badge,.walk-tools,.walk-badge,.walk-mini,#overviewPanel,.zoom-controls,.speed-controls{display:none!important}
.geo-badge{position:absolute;z-index:1200;left:50%;top:84px;transform:translateX(-50%);background:#07111de8;border:1px solid #526172;border-radius:999px;padding:7px 12px;color:#dbeafe;font:800 10px system-ui;letter-spacing:.08em;white-space:nowrap;pointer-events:none}.geo-controls{position:absolute;z-index:1300;right:max(12px,env(safe-area-inset-right));top:84px;display:flex;gap:8px;align-items:center}.geo-group{display:flex;align-items:center;background:#0f172ae8;border:1px solid #475569;border-radius:13px;overflow:hidden;box-shadow:0 7px 18px #0005}.geo-group button{border:0;border-right:1px solid #475569;background:transparent;color:#fff;min-width:42px;height:38px;padding:0 10px;font:850 12px system-ui}.geo-group button:last-child{border-right:0}.geo-group button.active{background:#2563eb}.geo-readout{min-width:62px;text-align:center;color:#dbeafe;font:800 11px system-ui;padding:0 8px}.geo-scale{position:absolute;z-index:1200;left:max(14px,env(safe-area-inset-left));bottom:max(188px,calc(env(safe-area-inset-bottom) + 188px));background:#07111ddd;border:1px solid #475569;border-radius:9px;padding:6px 9px;color:#e2e8f0;font:750 10px system-ui;pointer-events:none}.geo-scale-line{height:3px;background:#fff;margin-top:4px;min-width:30px}.geo-loading{position:absolute;z-index:1600;left:50%;top:50%;transform:translate(-50%,-50%);background:#07111ef2;border:1px solid #526172;border-radius:20px;padding:22px 26px;color:#fff;text-align:center;box-shadow:0 20px 60px #0009;min-width:280px}.geo-loading b{display:block;font-size:17px;margin-bottom:6px}.geo-loading span{font-size:12px;color:#cbd5e1}.action-wrap,.prompt{display:none!important}.legend{display:none!important}@media(max-width:740px){.geo-badge{top:62px;font-size:8px}.geo-controls{top:74px;right:9px;gap:5px;flex-direction:column;align-items:flex-end}.geo-group button{min-width:38px;height:34px;padding:0 8px;font-size:11px}.geo-readout{min-width:54px;font-size:10px}.geo-scale{bottom:160px;font-size:9px}.hud .stats{display:none}}
`;document.head.appendChild(css);
const gameEl=document.getElementById('game');
const badge=document.createElement('div');badge.className='geo-badge';badge.textContent='LEVEL 1 · TRUE-SCALE SHEPPERTON · OSM GEOMETRY';gameEl.appendChild(badge);
const controls=document.createElement('div');controls.className='geo-controls';controls.innerHTML='<div class="geo-group" id="speedGroup"><button data-speed="1" class="active">1×</button><button data-speed="2">2×</button><button data-speed="4">4×</button></div><div class="geo-group"><button id="zoomOut">−</button><span id="zoomRead" class="geo-readout"></span><button id="zoomIn">+</button></div>';gameEl.appendChild(controls);
const scale=document.createElement('div');scale.className='geo-scale';scale.innerHTML='<span id="scaleText">10 m</span><div id="scaleLine" class="geo-scale-line"></div>';gameEl.appendChild(scale);
const loading=document.createElement('div');loading.className='geo-loading hidden';loading.innerHTML='<b>Loading Shepperton geography…</b><span>Roads and buildings are being converted to the gameplay world.</span>';gameEl.appendChild(loading);

function xy(lat,lng){return{x:(lng-HOME.lng)*M_PER_DEG*COS,y:(HOME.lat-lat)*M_PER_DEG}}
function bb(pts){let minx=Infinity,miny=Infinity,maxx=-Infinity,maxy=-Infinity;for(const p of pts){if(p.x<minx)minx=p.x;if(p.y<miny)miny=p.y;if(p.x>maxx)maxx=p.x;if(p.y>maxy)maxy=p.y}return[minx,miny,maxx,maxy]}
function pathPts(way,nodes){const pts=[];for(const id of way.nodes||[]){const n=nodes.get(id);if(n)pts.push(xy(n.lat,n.lon))}return pts}
const roadTypes=new Set(['motorway','motorway_link','trunk','trunk_link','primary','primary_link','secondary','secondary_link','tertiary','tertiary_link','residential','unclassified','service','living_street','track']);
const pathTypes=new Set(['footway','path','cycleway','pedestrian','steps','bridleway']);
const greenTypes=new Set(['grass','meadow','recreation_ground','residential','retail','commercial','forest','allotments','cemetery','industrial','park','garden','playground','pitch','sports_centre','wood','scrub','grassland']);
async function overpass(){const q=`[out:json][timeout:60];(way["highway"](${BBOX.s},${BBOX.w},${BBOX.n},${BBOX.e});way["building"](${BBOX.s},${BBOX.w},${BBOX.n},${BBOX.e});way["barrier"](${BBOX.s},${BBOX.w},${BBOX.n},${BBOX.e});way["railway"](${BBOX.s},${BBOX.w},${BBOX.n},${BBOX.e});way["landuse"](${BBOX.s},${BBOX.w},${BBOX.n},${BBOX.e});way["leisure"](${BBOX.s},${BBOX.w},${BBOX.n},${BBOX.e});way["amenity"="parking"](${BBOX.s},${BBOX.w},${BBOX.n},${BBOX.e});way["natural"="water"](${BBOX.s},${BBOX.w},${BBOX.n},${BBOX.e}););out body;>;out skel qt;`;
 const endpoints=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'];let err;
 for(const url of endpoints){try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:'data='+encodeURIComponent(q)});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}catch(e){err=e}}
 throw err||Error('Unable to load OSM data');}
function parseOSM(data){const nodes=new Map(),ways=[];for(const e of data.elements||[]){if(e.type==='node')nodes.set(e.id,e);else if(e.type==='way')ways.push(e)}
 let bounds=[Infinity,Infinity,-Infinity,-Infinity];const addBounds=b=>{bounds[0]=Math.min(bounds[0],b[0]);bounds[1]=Math.min(bounds[1],b[1]);bounds[2]=Math.max(bounds[2],b[2]);bounds[3]=Math.max(bounds[3],b[3])};
 for(const w of ways){const t=w.tags||{},pts=pathPts(w,nodes);if(pts.length<2)continue;const b=bb(pts);addBounds(b);const h=t.highway;
  if(h&&roadTypes.has(h))world.roads.push({p:pts,b,t:h,n:t.name||'',lan:t.lanes||'',sw:t.sidewalk||'',width:t.width||''});
  else if(h&&pathTypes.has(h))world.paths.push({p:pts,b,t:h,n:t.name||''});
  else if(t.building&&pts.length>3)world.buildings.push({p:pts,b,t:t.building});
  else if(t.barrier)world.barriers.push({p:pts,b,t:t.barrier});
  else if(t.railway)world.rails.push({p:pts,b,t:t.railway});
  else if(t.amenity==='parking')world.parking.push({p:pts,b});
  else if(t.natural==='water')world.water.push({p:pts,b});
  else {const k=t.landuse||t.leisure||t.natural;if(k&&greenTypes.has(k))world.land.push({p:pts,b,k});}
 }
 world.bounds=bounds;loaded=true;loading.classList.add('hidden');toast(`${world.buildings.length} buildings · ${world.roads.length} roads loaded`);}
let loadPromise=null;function loadWorld(){if(loadPromise)return loadPromise;loadPromise=(async()=>{try{const d=await overpass();parseOSM(d)}catch(e){console.error(e);loadError=true;loading.innerHTML='<b>Map data could not load</b><span>Check your connection and refresh the game.</span>';loading.classList.remove('hidden')}})();return loadPromise}
loadWorld();

document.querySelectorAll('#speedGroup button').forEach(b=>b.onclick=()=>{speedMult=Number(b.dataset.speed);document.querySelectorAll('#speedGroup button').forEach(x=>x.classList.toggle('active',x===b));toast(`${speedMult}× travel · 1× is ${WALK_MPS.toFixed(2)} m/s`) });
document.getElementById('zoomOut').onclick=()=>setZoom(ppm/1.25);document.getElementById('zoomIn').onclick=()=>setZoom(ppm*1.25);
function setZoom(v){ppm=Math.max(MIN_PPM,Math.min(MAX_PPM,v));updateZoom()}
function updateZoom(){document.getElementById('zoomRead').textContent=Math.round(ppm/11*100)+'%';const m=ppm<7?20:ppm<14?10:5;document.getElementById('scaleText').textContent=m+' m';document.getElementById('scaleLine').style.width=(m*ppm)+'px'}updateZoom();
function roadWidth(r){const explicit=parseFloat(String(r.width).replace(/[^0-9.]/g,''));if(explicit>1&&explicit<50)return explicit;const lanes=parseInt(r.lan,10);if(Number.isFinite(lanes)&&lanes>0)return Math.max(3.6,lanes*3.6);return({motorway:22,motorway_link:8,trunk:14,trunk_link:8,primary:10,primary_link:7.5,secondary:7.2,secondary_link:6.8,tertiary:6.4,tertiary_link:6,residential:5.5,unclassified:5.2,service:4,living_street:4.5,track:3}[r.t]||5.2)}
function sidewalkExtra(r){if(r.t==='track'||r.t==='service')return .8;if(r.sw==='both')return 3.6;if(r.sw==='left'||r.sw==='right')return 1.8;return 3.0}
function visible(b,m=10){const hw=innerWidth/(2*ppm)+m,hh=innerHeight/(2*ppm)+m;return !(b[2]<cam.x-hw||b[0]>cam.x+hw||b[3]<cam.y-hh||b[1]>cam.y+hh)}
function line(pts){ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++)ctx.lineTo(pts[i].x,pts[i].y)}
function poly(pts){line(pts);ctx.closePath()}
function pointIn(x,y,pts){let inside=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++){const a=pts[i],b=pts[j];if(((a.y>y)!=(b.y>y))&&(x<(b.x-a.x)*(y-a.y)/(b.y-a.y+1e-12)+a.x))inside=!inside}return inside}
function segDist(px,py,a,b){const vx=b.x-a.x,vy=b.y-a.y,wx=px-a.x,wy=py-a.y,c=vx*vx+vy*vy;if(c<1e-9)return Math.hypot(px-a.x,py-a.y);let t=(vx*wx+vy*wy)/c;t=Math.max(0,Math.min(1,t));return Math.hypot(px-a.x-t*vx,py-a.y-t*vy)}
function buildingHit(x,y,f){if(x<f.b[0]-PLAYER_RADIUS||x>f.b[2]+PLAYER_RADIUS||y<f.b[1]-PLAYER_RADIUS||y>f.b[3]+PLAYER_RADIUS)return false;if(pointIn(x,y,f.p))return true;for(let i=1;i<f.p.length;i++)if(segDist(x,y,f.p[i-1],f.p[i])<PLAYER_RADIUS)return true;return false}
function blocked(x,y){if(!loaded)return true;if(world.bounds&&(x<world.bounds[0]||x>world.bounds[2]||y<world.bounds[1]||y>world.bounds[3]))return true;for(const f of world.buildings)if(buildingHit(x,y,f))return true;for(const f of world.barriers){if(x<f.b[0]-1||x>f.b[2]+1||y<f.b[1]-1||y>f.b[3]+1)continue;for(let i=1;i<f.p.length;i++)if(segDist(x,y,f.p[i-1],f.p[i])<PLAYER_RADIUS+.18)return true}return false}
function resize(){const d=Math.min(devicePixelRatio||1,2);const w=Math.floor(innerWidth*d),h=Math.floor(innerHeight*d);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize);resize();
function reset(){player.x=-7.2;player.y=.6;cam.x=player.x;cam.y=player.y;}
const prevStart=document.getElementById('startLife').onclick;document.getElementById('startLife').onclick=e=>{prevStart.call(document.getElementById('startLife'),e);if(!game.classList.contains('hidden')){reset();if(!loaded){loading.classList.remove('hidden');loadWorld()}else toast('True-scale Shepperton ready · buildings are locked.')}};
function move(dt){let dx=(keys.right?1:0)-(keys.left?1:0),dy=(keys.down?1:0)-(keys.up?1:0);if((!dx&&!dy)||!loaded)return;const len=Math.hypot(dx,dy);dx/=len;dy/=len;const s=WALK_MPS*speedMult*dt,nx=player.x+dx*s,ny=player.y+dy*s;if(!blocked(nx,player.y))player.x=nx;if(!blocked(player.x,ny))player.y=ny;state.minutes+=dt*speedMult/60;state.energy=Math.max(0,state.energy-dt*.0025*speedMult)}
update=function(dt){if(modalOpen||game.classList.contains('hidden'))return;move(dt);cam.x+=(player.x-cam.x)*Math.min(1,dt*8);cam.y+=(player.y-cam.y)*Math.min(1,dt*8);near=null;promptEl.classList.add('hidden');actionBtn.classList.remove('active');ui()};interact=function(){};
function drawLand(){for(const f of world.land){if(!visible(f.b,20))continue;poly(f.p);ctx.fillStyle=f.k==='residential'?'#456249':f.k==='industrial'?'#5b584c':f.k==='forest'||f.k==='wood'?'#284a33':f.k==='pitch'?'#3f7650':'#3e6a49';ctx.fill()}}
function drawRoads(){ctx.lineCap='round';ctx.lineJoin='round';for(const r of world.roads){if(!visible(r.b,30))continue;ctx.strokeStyle='#c9c5b2';ctx.lineWidth=roadWidth(r)+sidewalkExtra(r);line(r.p);ctx.stroke()}for(const r of world.roads){if(!visible(r.b,30))continue;ctx.strokeStyle=r.t==='track'?'#8d806a':'#646c6e';ctx.lineWidth=roadWidth(r);line(r.p);ctx.stroke()}ctx.strokeStyle='#eee3ac';ctx.setLineDash([2.8,3.5]);for(const r of world.roads){if(!visible(r.b,30)||!['motorway','trunk','primary','secondary','tertiary'].includes(r.t))continue;ctx.lineWidth=.16;line(r.p);ctx.stroke()}ctx.setLineDash([])}
function drawPaths(){ctx.lineCap='round';for(const p of world.paths){if(!visible(p.b,12))continue;ctx.strokeStyle='#d7d0b8';ctx.lineWidth=p.t==='cycleway'?2.4:p.t==='pedestrian'?3:1.8;line(p.p);ctx.stroke()}}
function drawBuildings(){for(const b of world.buildings){if(!visible(b.b,15))continue;poly(b.p);ctx.fillStyle=b.t==='house'||b.t==='residential'?'#b49b7c':'#a99377';ctx.fill();ctx.strokeStyle='#473b31';ctx.lineWidth=.2;ctx.stroke()}}
function drawOther(){for(const p of world.parking){if(!visible(p.b,15))continue;poly(p.p);ctx.fillStyle='#77796f';ctx.fill()}for(const r of world.rails){if(!visible(r.b,20))continue;ctx.strokeStyle='#2d3234';ctx.lineWidth=1.7;line(r.p);ctx.stroke();ctx.strokeStyle='#d5d5cf';ctx.lineWidth=.18;ctx.setLineDash([.6,.6]);line(r.p);ctx.stroke();ctx.setLineDash([])}if(ppm>8)for(const b of world.barriers){if(!visible(b.b,10))continue;ctx.strokeStyle=b.t==='hedge'?'#234c2c':'#5b4a3b';ctx.lineWidth=b.t==='hedge'?.55:.18;line(b.p);ctx.stroke()}}
function labels(){if(ppm<7)return;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#e6dfbd';ctx.strokeStyle='#3d4344';ctx.lineWidth=.28;ctx.font=`${Math.max(.75,10/ppm)}px system-ui`;const seen=new Set();for(const r of world.roads){if(!r.n||seen.has(r.n)||!visible(r.b,4)||r.p.length<2)continue;seen.add(r.n);const i=Math.floor((r.p.length-1)/2),a=r.p[i],b=r.p[i+1]||a;ctx.save();ctx.translate(a.x,a.y);let ang=Math.atan2(b.y-a.y,b.x-a.x);if(ang>Math.PI/2||ang<-Math.PI/2)ang+=Math.PI;ctx.rotate(ang);ctx.strokeText(r.n,0,0);ctx.fillText(r.n,0,0);ctx.restore()}}
function person(){ctx.save();ctx.translate(player.x,player.y);const id=character.avatar||'phil',shirt=id==='harry'?'#65734a':id==='matt'?'#d9e1e5':'#16191d',skin=id==='matt'?'#d99a70':'#e4b089';ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(0,.36,.35,.17,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=shirt;ctx.beginPath();ctx.ellipse(0,.05,.30,.42,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=skin;ctx.beginPath();ctx.arc(0,-.36,.22,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#14191e';ctx.lineWidth=.06;ctx.stroke();ctx.restore()}
draw=function(){resize();ctx.clearRect(0,0,innerWidth,innerHeight);ctx.save();ctx.translate(innerWidth/2,innerHeight/2);ctx.scale(ppm,ppm);ctx.translate(-cam.x,-cam.y);ctx.fillStyle='#35533d';const vw=innerWidth/ppm,vh=innerHeight/ppm;ctx.fillRect(cam.x-vw/2-20,cam.y-vh/2-20,vw+40,vh+40);if(loaded){drawLand();drawOther();drawRoads();drawPaths();drawBuildings();labels()}person();ctx.restore()};
let pinch=null;canvas.addEventListener('touchstart',e=>{if(e.touches.length===2){const a=e.touches[0],b=e.touches[1];pinch={d:Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY),z:ppm};e.preventDefault()}},{passive:false});canvas.addEventListener('touchmove',e=>{if(pinch&&e.touches.length===2){const a=e.touches[0],b=e.touches[1];setZoom(pinch.z*Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY)/pinch.d);e.preventDefault()}},{passive:false});canvas.addEventListener('touchend',e=>{if(e.touches.length<2)pinch=null},{passive:true});canvas.addEventListener('wheel',e=>{setZoom(ppm*(e.deltaY<0?1.12:.89));e.preventDefault()},{passive:false});
})();
